'use strict';

// tests for kovi-test
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('kovi-test', '/src/function/kovi-test.js', 'run');

describe('kovi-test', () => {
  before((done) => {
    done();
  });

  it('success test', () => {
    const firstArray = [1, 2, 3, 9, 12];
    const secondArray = [1, 9, 19, 12, 90, 9, 9, 9];
    const expectResult = [1, 9, 12];
    return wrapped.run({ firstArray, secondArray }).then((response) => {
      expect(response).to.equal(expectResult);
    });
  });
});
