function transpile(kind, data) {
    const map = {
        "pinBlock": 'pinBlock',
        "pan": 'pan',
        "stan": 'stan',
        "transactionMTICode": '',
        "transactionCode": '',
        "captureAmount": '',
        "settlementAmount": '',
        "schemeEntryDate": '',
        "captureTime": '',
        "captureDate": '',
        "settlementDate": '',
        "cardAcceptorCategoryCode": '',
        "panCountryCode": '',
        "captureEntryMode": '',
        "captureAcquirerCode": '',
        "captureTerminalId": '',
        "cardAcceptorId": '',
        "cardAcceptorDescription": '',
        "captureCurrencyCode": '',
        "settlementCurrencyCode": '',
        "capturePosData": '',
        orbitall2transaction: {
            // 'B052_PIN_DATA': '',
            // 'B002_PAN': '',
            'UUID': 'paymentMethod.paymentCardId',
            'MTI': 'capture.transactionKindCode',
            // 'B003_PROC_CODE': '',
            'B004_TXN_AMT': 'capture.amount',
            'B005_CH_STL_AMT': 'settlement.amount',
            'B007_GMT_DATE_TIME': 'capture.schemeEntryDate',
            'B012_LCL_TXN_TIME': [
                'capture.date', (value, str) => `${str} || ${value}`,
            ],
            'B013_LCL_TXN_DATE': [
                'capture.date', (value, str) => `${str} || ${value}`,
            ],
            'B015_REPRT_DATE': 'settlement.date',
            'B018_MER_TYPE': 'cardAcceptor.categoryCode',
            'B020_PAN_CNTRY_CODE': 'panCountryCode',
            'B022_POS_ENTRY_MDE': 'capture.entryMode',
            'B032_ACQ_ID': 'capture.acquirerCode',
            'B041_CRD_ACCPT_TRM': 'capture.terminalId',
            'B042_CRD_ACCPT_ID': 'cardAccpetor.id',
            'B043_CRD_ACCPT_NME': ['cardAcceptor',(value) => ({
                name: '',
                city: '',
                country: '',
            })],
            'B049_CURR_CODE': 'capture.currency',
            'B050_SETL_CUR_CODE': 'settlement.currency',
            'B061_POS_DATA': 'capture.posData',
            // 'B038_AUTH_CODE': '', vamos receber da orbitall
            'COD_RETORNO': '',
            'DES_RETORNO': '',
        }
    }
}